added NotFound component + routes
html-hooliganz/product_catalog_frontend pull request #8
Opened 2023-07-31 17:25 UTC by dimoshen

added NotFoundRedirect page + NotFound component with some custom errror page

2023-07-31 20:14 UTC, Ihor-Karpyn commented
Could u provide screenshots with UI changes?

2023-07-31 21:24 UTC, ruslanpashkov requested changes
Please refactor the `NotFound.scss` file following best practices from our project

2023-07-31 21:24 UTC, ruslanpashkov commented on src/App.tsx
> +import NotFound from './components/NotFound/NotFound';
It's a page, move it in `src/pages/` folder

2023-07-31 21:24 UTC, ruslanpashkov commented on src/App.tsx
> +        element: <NotFound />,
```suggestion
        element: <NotFoundPage />,
```

2023-07-31 21:24 UTC, ruslanpashkov commented on src/components/NotFound/NotFound.tsx
> +        </div>
```suggestion
        <h2 className="header" data-text="404">
          404
        </h2>

        <h4 data-text="Opps! Page not found">
            Oops! Page not found
        </h4>

        <p>
          Sorry, the page you&apos;re looking for doesn&apos;t exist.
        </p>

        <div className="button">
          <Link to ="/">Return Home</Link>
        </div>
```

2023-07-31 21:24 UTC, ruslanpashkov commented on src/components/NotFound/NotFound.tsx
> +        <h4 data-text="Opps! Page not found">
Do we need this data attribute here?

2023-07-31 21:24 UTC, ruslanpashkov commented on src/components/NotFound/NotFound.tsx
> +    <div id="error-page">
Let's use `className` instead. Also we use BEM on our project, so name all classes more appropriately

2023-07-31 21:24 UTC, ruslanpashkov commented on src/pages/NotFoundRedirect.tsx
We don't use this file anywhere, let's remove it

2023-07-31 21:24 UTC, ruslanpashkov commented on src/components/NotFound/NotFound.scss
BEM 😭

2023-07-31 21:24 UTC, ruslanpashkov commented on src/components/NotFound/NotFound.scss
> +    }
Create a separate `_keyframes.scss` file in `src/styles/utils` and give more descriptive name for keyframe

2023-07-31 21:24 UTC, ruslanpashkov commented on src/components/NotFound/NotFound.scss
> +        transition: all 0.3s ease;
Don't use transitions for all properties, use transitions only for the specific styles

2023-08-01 09:59 UTC, dimoshen commented on src/App.tsx
> +import NotFound from './components/NotFound/NotFound';
removed

2023-08-01 10:00 UTC, dimoshen commented on src/components/NotFound/NotFound.tsx
> +        <h4 data-text="Opps! Page not found">
removed. fixed content in the 'after'

2023-08-01 10:00 UTC, dimoshen commented on src/components/NotFound/NotFound.tsx
> +    <div id="error-page">
added classNames

2023-08-01 10:01 UTC, dimoshen commented on src/components/NotFound/NotFound.scss
fixed :)

2023-08-01 10:01 UTC, dimoshen commented on src/components/NotFound/NotFound.scss
> +    }
fixed

2023-08-01 12:20 UTC, merged